title: "CS 318: Principles of Operating Systems, Fall 2017"
email: huang@cs.jhu.edu
description: > # this means to ignore newlines until "baseurl:"
  Operating System course 2017 Fall semester at Johns Hopkins University.
  Instructor Prof. Ryan Huang.
meta_desc: jhu cs 318 fall 2017
# baseurl: "/teaching/fa17/cs318" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ryanphuang
github_username:  ryanphuang

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
navigation:
  - title: Home
    url: /index.html
  - title: Syllabus
    url: /syllabus.html
  - title: Homework
    url: /homework.html
  - title: Projects
    url: /projects.html
    dropdown:
      - title: Guide
        url: /project/guide.html
      - title: Setup
        url: /project/setup.html
      - separator: true
      - title: Lab 0 
        url: /project/project0.html
      - title: Lab 1 
        url: /project/project1.html
      - title: Lab 2 
        url: /project/project2.html
      - title: Lab 3 
        url: /project/project3.html
      - title: Lab 4 
        url: /project/project4.html
  - title: References
    url: /references.html
  - title: Piazza
    url: https://piazza.com/jhu/fall2017/cs318418618
